apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nodejs-container
        image: kapoorpriyanka/web-application:5
        imagePullPolicy: IfNotPresent #Added for showing rolling updates
        resources:
          requests:
            memory: "250Mi"  #Added to showcase scale up and down using HPA on Standard Cluster
            cpu: "250m"
          limits:
            memory: "500Mi"  #Added to showcase scale up and down using HPA on Standard Cluster
            cpu: "500m"

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
           name: app-settings
        - secretRef:
            name: mongodb-pass

