apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nodejs-container
        image: kapoorpriyanka/web-application:5
        imagePullPolicy: Always #Added for showing rolling updates
        resources:
          requests:
            memory: "250Mi"  #Added to showcase scale up and down using HPA on Standard Cluster
            cpu: "250m"
          limits:
            memory: "500Mi"  #Added to showcase scale up and down using HPA on Standard Cluster
            cpu: "500m"

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
           name: app-settings
        - secretRef:
            name: mongodb-pass

---
apiVersion: v1
kind: Service
metadata:
  name: node-service-lb
  namespace: default
  labels:
    app: node-service-lb
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: node-app
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  namespace: default
  name: node-app-deployment-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
