apiVersion: v1
kind: Service
metadata:
  name: node-service-lb
  namespace: default
  labels:
    app: node-service-lb
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: node-app
  type: LoadBalancer